### PR TITLE
Adds ability to remove prefix from git tag.

### PR DESCRIPTION
**Pull request by Nossnevs**

### CODE REVIEW

**Comment by deepy** [comment]
There's something not quite right here
```
» git tag -a v3.0.0 -m test;gradle showVersion;git tag -d v3.0.0

> Task :showVersion
Version: v3.0.0
```

**Review by deepy — CHANGES_REQUESTED** [review]
As it stands the prefix is being included in the output, but apart from that it seems good.

**Comment by Nossnevs** [comment]
@deepy I would appreciate a review/merge/release on this.

**Comment by deepy** [comment]
I'm back from my vacation, but I've lost access to the repository, so can't really do anything 🤷‍♀️

**Pull request merged**
