### PR TITLE
Add lightweight tag support

### PR DESCRIPTION
**Pull request by franktominc**
The plugin doesn't support lightweight tags when checking for the next version; this pull request aims to add support for those.

### CODE REVIEW

**Comment by franktominc** [comment]
@deepy can you check this one?

**Comment by franktominc** [comment]
@MikaelUmaN

**Comment by deepy** [comment]
Out of curiosity, why would you want to use lightweight tags for versions?
There's so many benefits to annotated tags *especially* when using them for versions.

**Comment by franktominc** [comment]
I know. I have a problem with Gitlab, the UI to create a tag is a little confusing, if you don't provide a message it creates a lightweight tag, and since I'm not the only one releasing the project I can't control if the user will provide a message or not. The application uses Rugged for repo management, and that is Rugged's default behavior https://www.rubydoc.info/gems/rugged/0.19.0/Rugged%2FTag.create

**Comment by franktominc** [comment]
@deepy Sorry for the ping, any update on this?

**Comment by deepy** [comment]
Sorry about the delay, while lightweight tags are pretty useless (in that they have no identity so you can't even tell who created the tag or when) I guess supporting them is fine, I'll do some testing and if all looks good I'll release an update tomorrow.
Otherwise I'll add a toggle, default it to off, and release an update tomorrow.

**Comment by deepy** [comment]
There's been a few updates since we last released and the signing plugin is messing with the `publishPlugins` so this'll take a little while longer unfortunately

**Comment by franktominc** [comment]
No worries, take your time

**Comment by deepy** [comment]
@franktominc it's available on the plugin portal now and will probably appear in central in less than an hour.

**Comment by franktominc** [comment]
Hi @deepy, thanks for the update, I'll look into it

**Pull request merged**
